#yml的版本是2，指定本 yml 依从的 compose 哪个版本制定的
version: '2'
networks:
  #aliases ：同一网络上的其他容器可以使用服务名称或此别名来连接到对应容器的服务。
  myspringbootnet:
services:
  my-app:
    #到ghost目录构建
    image: "192.168.236.128:5000/studyspringboot"
    container_name: studyspringboot
    networks:
    - myspringbootnet
    # depends_on 配置是容器的启动顺序, 并不是容器中服务的启动顺序.
    depends_on:
      - db-mysql
      - db-redis
      - rabbitmq
    #以下两行是设置服务启动顺序
  #  volumes:
   #   - "./wait-for.sh:/wait-for.sh"
   # entrypoint: sh /wait-for.sh db-mysql:3306,db-redis:6379,rabbitmq:5672 -- java  -jar /app.jar
    ports:
      - "8882:8882"

  nginx:
    #到当前目录构建
    build: nginx
    container_name: mynginx
    networks:
    - myspringbootnet
    depends_on:
    - my-app
    ports:
    - "80:80"

  db-mysql:
    image: "pre-mysql:1.0.0"
    container_name: db-mysql
    networks:
    - myspringbootnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bee
      MYSQL_PASSWORD: 123456
   # volumes:
   # - $PWD/data/mysql:/var/lib/mysql
    ports:
    - "3306:3306"

  db-redis:
    image: "hub.c.163.com/library/redis:3.2.9"
    container_name: db-redis
    networks:
    - myspringbootnet
    volumes:
    - $PWD/data/redis:/data
    ports:
    - "6379:6379"

  rabbitmq:
    image: hub.c.163.com/summermango/rabbitmq-management-3.6.5
    container_name: rabbitmqCNM
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
    restart: always
    ports:
    - "15672:15672"
    - "5672:5672"